
- hosts:
  - localhost
  tasks:

     - name: Add lxd monitoring 
       shell: |
                docker run -d --name lxd-dashboard -p 80:80 -e ADMIN_PASS="lxdware" -v ~/lxdware:/var/lxdware --restart=always lxdware/dashboard:1.2.8


- hosts:
  - localhost
  tasks:

     - name: change to kustomize file directory for metallb
       shell: |
               cd ../kustomize/metallb
               kustomize build .   --enable-helm |kubectl apply -f -