
- hosts:
  - localhost
  tasks:

    # - name: Add lxd monitoring 
    #   shell: |
    #             docker run -d --name lxd-dashboard -p 80:80 -e ADMIN_PASS="lxdware" -v ~/lxdware:/var/lxdware --restart=always lxdware/dashboard:1.2.8

    - name: Add k8s dashboard 
      shell: |
                kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.5.1/aio/deploy/recommended.yaml


    - name: Create kube-dashboard-admin.yaml
      file:
          path: "/tmp/kube-dashboard-admin.yaml"
          state: touch
          mode: 0755
          owner: gk

    - name: add  kubeadm-config.yaml file  content
      copy:
          force: yes
          dest: "/tmp/kube-dashboard-admin.yaml"
          content: |
                   
                    ---
                    apiVersion: v1
                    kind: ServiceAccount
                    metadata:
                      name: kube-dashboard-admin
                      namespace: kube-system
                    ---
                    apiVersion: rbac.authorization.k8s.io/v1
                    kind: ClusterRoleBinding
                    metadata:
                      name: kube-dashboard-admin
                    roleRef:
                      apiGroup: rbac.authorization.k8s.io
                      kind: ClusterRole
                      name: cluster-admin
                    subjects:
                    - kind: ServiceAccount
                      name: kube-dashboard-admin
                      namespace: kube-system    


    - name: Add k8s dashboard 
      shell: |
                kubectl apply -f /tmp/kube-dashboard-admin.yaml
                kubectl -n kube-system get secret $(kubectl get sa kube-dashboard-admin -n kube-system  -o=jsonpath='{.secrets[].name}')  -o=jsonpath='{.data.token}' |base64 --decode> token.txt