
- hosts:
  - localhost
  become: true
  become_method: sudo
  become_user: root
  tasks:

     - name: add kubeseal prerequiste for kubeflow 
       shell: |
            sudo wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.5/kubeseal-0.17.5-linux-amd64.tar.gz  
            sudo tar -xvfz kubeseal-0.17.5-linux-amd64.tar.gz
            sudo mv kubeseal /usr/local/bin/kubeseal
            sudo chmod 755 /usr/local/bin/kubeseal
            
            #targetRevision: 2.1.8
