- hosts:
  - localhost
  tasks:

    - name: change to kustomize file directory for metallb
      shell: |
               cd ../kustomize/metallb
               kustomize build .   --enable-helm |kubectl apply -f -

    - name: wait for pods to come up
      shell: kubectl get pods -o json
      register: kubectl_get_pods
      until: kubectl_get_pods.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
      retries: 10
      delay: 30

    # - name: Wait for all control-plane pods become created
    #   shell: "kubectl get po --namespace=kube-system --selector tier=control-plane --output=jsonpath='{.items[*].metadata.name}'"
    #   register: control_plane_pods_created
    #   until: item in control_plane_pods_created.stdout
    #   retries: 10
    #   delay: 30
    #   with_items:
    #     - etcd
    #     - kube-apiserver
    #     - kube-controller-manager
    #     - kube-scheduler

    # - name: Wait for control-plane pods become ready
    #   shell: "kubectl wait --namespace=kube-system --for=condition=Ready pods --selector tier=control-plane --timeout=600s"
    #   register: control_plane_pods_ready

    # - debug: var=control_plane_pods_ready.stdout_lines