
- hosts:
  - localhost

  gather_facts: yes


  tasks:

            - name: Creating a file with content
              copy:
                  dest: ../kustomize/nfs-provisioner/base/namespace.yaml
                  content: |
                      apiVersion: v1
                      kind: Namespace
                      metadata:
                        creationTimestamp: null
                        name: nfs-provisioner
                      spec: {}
                      status: {}

- hosts:
  - localhost

  gather_facts: yes


  tasks:

            - name: Creating a file with content
              copy:
                  dest: ../kustomize/nfs-provisioner/base/kustomization.yaml
                  content: |
                    helmCharts:
                    - name: nfs-subdir-external-provisioner
                      repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
                      releaseName: nfs-subdir-external-provisioner
                      valuesInline: 
                        nfs:
                                server: "{{ hostvars['nfsserver0'].ip_address }}"
                                path: /nfs-storage



# # # TODO kubectl patch storageclass nfs-client -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

# #      - name: patch storageclass nfs-client as default storage class 
# #        kubernetes.core.k8s:
# #           state: patched
# #           kind: StorageClass
# #           name: nfs-client
# #           definition:
# #             metadata:
# #               annotations:
# #                 storageclass.kubernetes.io/is-default-class: "true"